"""Template configuration: load and validate a per-template YAML config."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml


@dataclass
class TemplateConfig:
    """Per-template configuration declaring shape name ↔ data field mapping.

    One config file per pptx template. The config decouples the template's
    internal shape names (which vary per template) from the data fields
    (which stay consistent across templates).
    """

    template: Path
    """Path to the source pptx/pptm template."""

    source_slide_index: int = 1
    """1-based index of the slide inside the template that should be
    duplicated per record. Usually the 'filled example' slide."""

    placeholders: dict[str, str] = field(default_factory=dict)
    """Mapping from data field name (key) to shape .Name in the template (value).

    Example:
        placeholders:
          name: Consultant_Name
          role: Role_Title
          background: Background_Bullets
    """

    clear_source_slide: bool = True
    """If True, the source (example) slide is removed from the final output
    so only the generated per-record slides remain."""

    bullet_join: str = "\n"
    """String to split multi-line text on when setting a shape with a scalar
    string that contains newlines. Also used when the data value is a list
    to detect if items should become separate paragraphs."""

    def validate(self) -> list[str]:
        """Return a list of validation error messages, or empty list if OK."""
        errors: list[str] = []
        if not self.template.exists():
            errors.append(f"Template file not found: {self.template}")
        if self.source_slide_index < 1:
            errors.append(f"source_slide_index must be >= 1 (got {self.source_slide_index})")
        if not self.placeholders:
            errors.append("placeholders mapping is empty — at least one field is required")
        return errors


def load_config(path: Path | str) -> TemplateConfig:
    """Load a TemplateConfig from a YAML file.

    Resolves the `template` path relative to the config file's directory
    unless it's absolute.
    """
    path = Path(path).expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")

    with path.open("r", encoding="utf-8") as fh:
        data: dict[str, Any] = yaml.safe_load(fh) or {}

    template_path_raw = data.get("template")
    if template_path_raw is None:
        raise ValueError(f"{path}: missing required key 'template'")

    template_path = Path(template_path_raw).expanduser()
    if not template_path.is_absolute():
        template_path = (path.parent / template_path).resolve()

    config = TemplateConfig(
        template=template_path,
        source_slide_index=int(data.get("source_slide_index", 1)),
        placeholders=dict(data.get("placeholders", {}) or {}),
        clear_source_slide=bool(data.get("clear_source_slide", True)),
        bullet_join=str(data.get("bullet_join", "\n")),
    )

    errors = config.validate()
    if errors:
        joined = "\n  - ".join(errors)
        raise ValueError(f"{path}: config validation failed:\n  - {joined}")

    return config


def write_scaffold_config(
    template_path: Path,
    shape_names: list[str],
    output_path: Path,
) -> None:
    """Write a starter config file from a list of shape names.

    The user then edits the placeholders section to map semantic field names
    to the actual shape names they want to populate.
    """
    lines = [
        f"# Template config for {template_path.name}",
        "# Generated by `recombinase inspect --write-config`.",
        "# Edit the placeholders section to map your data fields to shape names.",
        "",
        f"template: {template_path}",
        "source_slide_index: 1",
        "clear_source_slide: true",
        "",
        "# placeholders: data_field_name → shape_name_in_template",
        "placeholders:",
    ]
    if shape_names:
        for name in shape_names:
            slug = name.lower().replace(" ", "_").replace("-", "_").replace(".", "_")
            lines.append(f"  {slug}: {name}")
    else:
        lines.append("  # (no named shapes found — template has only default names)")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
